### ISSUE TITLE
Postgres 14

### ISSUE THREAD

**Issue by idevloo** [ossc-db/pg_store_plans#14]
Hi,

Any idea if this extension is compatible with PostgreSQL 14beta3 on x86_64-pc-linux-gnu

While running the make, I'm getting : 

root@milespgdb2:/usr/pgsql-14/share/contrib/pg_store_plans # make
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fPIC -fPIC -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pg_store_plans.o pg_store_plans.c
pg_store_plans.c: In function ‘_PG_init’:
pg_store_plans.c:440:22: warning: assignment from incompatible pointer type [enabled by default]
  ProcessUtility_hook = pgsp_ProcessUtility;
                      ^
pg_store_plans.c: In function ‘pgsp_ExecutorStart’:
pg_store_plans.c:713:3: error: too few arguments to function ‘InstrAlloc’
   queryDesc->totaltime = InstrAlloc(1, INSTRUMENT_ALL);
   ^
In file included from /usr/pgsql-14/include/server/nodes/execnodes.h:18:0,
                 from /usr/pgsql-14/include/server/executor/execdesc.h:18,
                 from /usr/pgsql-14/include/server/executor/executor.h:17,
                 from /usr/pgsql-14/include/server/commands/explain.h:16,
                 from pg_store_plans.c:40:
/usr/pgsql-14/include/server/executor/instrument.h:100:25: note: declared here
 extern Instrumentation *InstrAlloc(int n, int instrument_options,
                         ^
pg_store_plans.c: In function ‘pgsp_ProcessUtility’:
pg_store_plans.c:836:8: error: incompatible type for argument 4 of ‘prev_ProcessUtility’
        dest, completionTag);
        ^
pg_store_plans.c:836:8: note: expected ‘ProcessUtilityContext’ but argument is of type ‘ParamListInfo’
pg_store_plans.c:836:8: warning: passing argument 5 of ‘prev_ProcessUtility’ from incompatible pointer type [enabled by default]
pg_store_plans.c:836:8: note: expected ‘ParamListInfo’ but argument is of type ‘struct QueryEnvironment *’
pg_store_plans.c:836:8: warning: passing argument 6 of ‘prev_ProcessUtility’ from incompatible pointer type [enabled by default]
pg_store_plans.c:836:8: note: expected ‘struct QueryEnvironment *’ but argument is of type ‘struct DestReceiver *’
pg_store_plans.c:836:8: warning: passing argument 7 of ‘prev_ProcessUtility’ from incompatible pointer type [enabled by default]
pg_store_plans.c:836:8: note: expected ‘struct DestReceiver *’ but argument is of type ‘struct QueryCompletion *’
pg_store_plans.c:836:8: error: too few arguments to function ‘prev_ProcessUtility’
pg_store_plans.c:840:9: error: incompatible type for argument 4 of ‘standard_ProcessUtility’
         dest, completionTag);
         ^
In file included from pg_store_plans.c:51:0:
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: expected ‘ProcessUtilityContext’ but argument is of type ‘ParamListInfo’
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^
pg_store_plans.c:840:9: warning: passing argument 5 of ‘standard_ProcessUtility’ from incompatible pointer type [enabled by default]
         dest, completionTag);
         ^
In file included from pg_store_plans.c:51:0:
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: expected ‘ParamListInfo’ but argument is of type ‘struct QueryEnvironment *’
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^
pg_store_plans.c:840:9: warning: passing argument 6 of ‘standard_ProcessUtility’ from incompatible pointer type [enabled by default]
         dest, completionTag);
         ^
In file included from pg_store_plans.c:51:0:
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: expected ‘struct QueryEnvironment *’ but argument is of type ‘struct DestReceiver *’
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^
pg_store_plans.c:840:9: warning: passing argument 7 of ‘standard_ProcessUtility’ from incompatible pointer type [enabled by default]
         dest, completionTag);
         ^
In file included from pg_store_plans.c:51:0:
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: expected ‘struct DestReceiver *’ but argument is of type ‘struct QueryCompletion *’
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^
pg_store_plans.c:840:9: error: too few arguments to function ‘standard_ProcessUtility’
         dest, completionTag);
         ^
In file included from pg_store_plans.c:51:0:
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: declared here
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^
pg_store_plans.c: In function ‘pg_store_plans’:
pg_store_plans.c:1043:57: error: ‘DEFAULT_ROLE_READ_ALL_STATS’ undeclared (first use in this function)
  bool  is_allowed_role = is_member_of_role(GetUserId(), DEFAULT_ROLE_READ_ALL_STATS);
                                                         ^
pg_store_plans.c:1043:57: note: each undeclared identifier is reported only once for each function it appears in
make: *** [pg_store_plans.o] Error 1
root@milespgdb2:/usr/pgsql-14/share/contrib/pg_store_plans # make
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fPIC -fPIC -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pg_store_plans.o pg_store_plans.c
pg_store_plans.c: In function ‘_PG_init’:
pg_store_plans.c:440:22: warning: assignment from incompatible pointer type [enabled by default]
  ProcessUtility_hook = pgsp_ProcessUtility;
                      ^
pg_store_plans.c: In function ‘pgsp_ExecutorStart’:
pg_store_plans.c:713:3: error: too few arguments to function ‘InstrAlloc’
   queryDesc->totaltime = InstrAlloc(1, INSTRUMENT_ALL);
   ^
In file included from /usr/pgsql-14/include/server/nodes/execnodes.h:18:0,
                 from /usr/pgsql-14/include/server/executor/execdesc.h:18,
                 from /usr/pgsql-14/include/server/executor/executor.h:17,
                 from /usr/pgsql-14/include/server/commands/explain.h:16,
                 from pg_store_plans.c:40:
/usr/pgsql-14/include/server/executor/instrument.h:100:25: note: declared here
 extern Instrumentation *InstrAlloc(int n, int instrument_options,
                         ^
pg_store_plans.c: In function ‘pgsp_ProcessUtility’:
pg_store_plans.c:836:8: error: incompatible type for argument 4 of ‘prev_ProcessUtility’
        dest, completionTag);
        ^
pg_store_plans.c:836:8: note: expected ‘ProcessUtilityContext’ but argument is of type ‘ParamListInfo’
pg_store_plans.c:836:8: warning: passing argument 5 of ‘prev_ProcessUtility’ from incompatible pointer type [enabled by default]
pg_store_plans.c:836:8: note: expected ‘ParamListInfo’ but argument is of type ‘struct QueryEnvironment *’
pg_store_plans.c:836:8: warning: passing argument 6 of ‘prev_ProcessUtility’ from incompatible pointer type [enabled by default]
pg_store_plans.c:836:8: note: expected ‘struct QueryEnvironment *’ but argument is of type ‘struct DestReceiver *’
pg_store_plans.c:836:8: warning: passing argument 7 of ‘prev_ProcessUtility’ from incompatible pointer type [enabled by default]
pg_store_plans.c:836:8: note: expected ‘struct DestReceiver *’ but argument is of type ‘struct QueryCompletion *’
pg_store_plans.c:836:8: error: too few arguments to function ‘prev_ProcessUtility’
pg_store_plans.c:840:9: error: incompatible type for argument 4 of ‘standard_ProcessUtility’
         dest, completionTag);
         ^
In file included from pg_store_plans.c:51:0:
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: expected ‘ProcessUtilityContext’ but argument is of type ‘ParamListInfo’
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^
pg_store_plans.c:840:9: warning: passing argument 5 of ‘standard_ProcessUtility’ from incompatible pointer type [enabled by default]
         dest, completionTag);
         ^
In file included from pg_store_plans.c:51:0:
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: expected ‘ParamListInfo’ but argument is of type ‘struct QueryEnvironment *’
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^
pg_store_plans.c:840:9: warning: passing argument 6 of ‘standard_ProcessUtility’ from incompatible pointer type [enabled by default]
         dest, completionTag);
         ^
In file included from pg_store_plans.c:51:0:
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: expected ‘struct QueryEnvironment *’ but argument is of type ‘struct DestReceiver *’
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^
pg_store_plans.c:840:9: warning: passing argument 7 of ‘standard_ProcessUtility’ from incompatible pointer type [enabled by default]
         dest, completionTag);
         ^
In file included from pg_store_plans.c:51:0:
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: expected ‘struct DestReceiver *’ but argument is of type ‘struct QueryCompletion *’
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^
pg_store_plans.c:840:9: error: too few arguments to function ‘standard_ProcessUtility’
         dest, completionTag);
         ^
In file included from pg_store_plans.c:51:0:
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: declared here
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^
pg_store_plans.c: In function ‘pg_store_plans’:
pg_store_plans.c:1043:57: error: ‘DEFAULT_ROLE_READ_ALL_STATS’ undeclared (first use in this function)
  bool  is_allowed_role = is_member_of_role(GetUserId(), DEFAULT_ROLE_READ_ALL_STATS);
                                                         ^
pg_store_plans.c:1043:57: note: each undeclared identifier is reported only once for each function it appears in
make: *** [pg_store_plans.o] Error 1

**Comment by yamatattsu** [comment]
Hi idevloo,

Sorry for the late reply.
We have started to revise pg_store_plans on PG14 from today. :-D

Regareds,
Tatsuro Yamada

**Comment by idevloo** [comment]
Hi Tatsuro,

Any expected time of arrival ?

How are things progressing ?

Thanks,
Ivan

**Comment by yamatattsu** [comment]
Hi Ivan,

Can you try this commit?
https://github.com/ossc-db/pg_store_plans/commit/5121fd3d0c6a409db1da077f064dd38a0d26f359 

Thanks,
Tatsuro Yamada

**Comment by idevloo** [comment]
Hi,

I’ll try to install this commit to my postgresql version 14.

I’ll keep you informed

Thanks,
Ivan

**Comment by yamatattsu** [comment]
Hi Ivan,

>5121fd3

Sorry, there are wrong commits history on the master branch. 
I'll let you know when it was fixed.

Regards,
Tatsuro Yamada

**Comment by idevloo** [comment]
ok

**Comment by idevloo** [comment]
Hi Tatsuro,

Can you please indicate what the status is now ? 

Can I start some testing ?

Thanks
Ivan

**Comment by yamatattsu** [comment]
Hi Ivan,

Sorry for the late reply.
As you might know, pg_store_plans 1.6 was released two days ago.

    https://github.com/ossc-db/pg_store_plans/releases/tag/1.6

Hope it helps.

Thanks,
Tatsuro Yamada

**Comment by BillSmith-EDB** [comment]
@idevloo @yamatattsu I'm able to compile v1.6 & v1.6.1 against v14 of PG successfully.  I think this issue can be closed.  Thoughts?

**Comment by yamatattsu** [comment]
@BillSmith-EDB 
Yeah, agreed.
I closed this issue as well as the issue below:
https://github.com/ossc-db/pg_store_plans/issues/13
