### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by lfittl** [ossc-db/pg_store_plans#4]
This looks like a useful extension, however it is missing a LICENSE file.

Could you confirm which license this code is under and add the file?

Thanks!

**Comment by yamatattsu** [comment]
Horiguchi-san will answer you tommorow maybe. :)

2018年12月10日(月) 15:45 Lukas Fittl <notifications@github.com>:

**Comment by lfittl** [comment]
@yamatattsu Any news on this?

I had a conversation in person at PGConf.ASIA about this, but would still need to see the license updated on this library to be able to use it.

Thanks :)

**Comment by lfittl** [comment]
@yamatattsu Thank you!

That looks good and I will hereby close this issue.

I appreciate your work on this & looking forward to make use of pg_store_plans :)

Thanks,
Lukas
