### ISSUE TITLE
PG13 compatibility

### ISSUE THREAD

**Issue by legrandlegrand** [ossc-db/pg_store_plans#5]
Hello,
it seems version 1.4 is not compatible with postgresql version 13:

ub64@ub64-Virtual-Machine:~/Downloads/postgresql-13devel/contrib/pg_store_plans$ make 
make -C ../../src/backend generated-headers
make[1]: Entering directory '/home/ub64/Downloads/postgresql-13devel/src/backend'
make -C catalog distprep generated-header-symlinks
make[2]: Entering directory '/home/ub64/Downloads/postgresql-13devel/src/backend/catalog'
make[2]: Nothing to be done for 'distprep'.
make[2]: Nothing to be done for 'generated-header-symlinks'.
make[2]: Leaving directory '/home/ub64/Downloads/postgresql-13devel/src/backend/catalog'
make -C utils distprep generated-header-symlinks
make[2]: Entering directory '/home/ub64/Downloads/postgresql-13devel/src/backend/utils'
make[2]: Nothing to be done for 'distprep'.
make[2]: Nothing to be done for 'generated-header-symlinks'.
make[2]: Leaving directory '/home/ub64/Downloads/postgresql-13devel/src/backend/utils'
make[1]: Leaving directory '/home/ub64/Downloads/postgresql-13devel/src/backend'
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -O2 -fPIC -fPIC -I. -I. -I../../src/include  -D_GNU_SOURCE   -c -o pg_store_plans.o pg_store_plans.c
pg_store_plans.c: In function ‘_PG_init’:
pg_store_plans.c:434:22: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
  ProcessUtility_hook = pgsp_ProcessUtility;
                      ^
pg_store_plans.c: In function ‘pgsp_ProcessUtility’:
pg_store_plans.c:830:14: warning: passing argument 7 of ‘prev_ProcessUtility’ from incompatible pointer type [-Wincompatible-pointer-types]
        dest, completionTag);
              ^~~~~~~~~~~~~
pg_store_plans.c:830:14: note: expected ‘QueryCompletion * {aka struct QueryCompletion *}’ but argument is of type ‘char *’
pg_store_plans.c:834:15: warning: passing argument 7 of ‘standard_ProcessUtility’ from incompatible pointer type [-Wincompatible-pointer-types]
         dest, completionTag);
               ^~~~~~~~~~~~~
In file included from pg_store_plans.c:51:0:
../../src/include/tcop/utility.h:82:13: note: expected ‘QueryCompletion * {aka struct QueryCompletion *}’ but argument is of type ‘char *’
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^~~~~~~~~~~~~~~~~~~~~~~
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -O2 -fPIC -fPIC -I. -I. -I../../src/include  -D_GNU_SOURCE   -c -o pgsp_json.o pgsp_json.c
pgsp_json.c:22:10: fatal error: utils/jsonapi.h: No such file or directory
 #include "utils/jsonapi.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'pgsp_json.o' failed
make: *** [pgsp_json.o] Error 1

**Comment by devrimgunduz** [comment]
Hi,

ping. v13 is out today. We need a v13 compatible release.

Regards, Devrim

**Comment by devrimgunduz-edb** [comment]
ping again.

**Comment by mbanck** [comment]
Seems this got fixed in 155ba93fce223435410a9e18de1a3e90a9893ddc but no new release has been made yet.

**Comment by legrandlegrand** [comment]
this has been adressed
